name: Linux

on:
  push:
    branches: [ "master" ]
  pull_request:
    branches: [ "master" ]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout repository with submodules
      uses: actions/checkout@v4
      with:
        submodules: recursive

    - name: Install dependencies
      run: |
        sudo apt-get update
        sudo apt-get install -y \
          build-essential \
          cmake \
          libev-dev \
          libevdev-dev \
          pkg-config \
          libgl1-mesa-dev \
          libglu1-mesa-dev \
          libx11-dev \
          libxrandr-dev \
          libxi-dev \
          libegl1-mesa-dev \
          libavcodec-dev \
          libavformat-dev \
          libavutil-dev \
          libswresample-dev \
          libswscale-dev \
          libudev-dev

    - name: Create build directory
      run: mkdir build

    - name: Configure CMake
      working-directory: build
      env:
        CMAKE_POLICY_VERSION_MINIMUM: "3.5"
      run: cmake .. -DLINUX_LOCAL_DEV=true

    - name: Compile with make
      working-directory: build
      run: make -j$(nproc)

    - name: Verify Build Success
      if: success()
      run: echo "✅ Build completed successfully!"

    - name: Notify on Failure
      if: failure()
      run: echo "❌ Build failed!"
