name: Linux

on:
  push:
    branches: [ "master" ]
  pull_request:
    branches: [ "master" ]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout repository with submodules
      uses: actions/checkout@v4
      with:
        submodules: recursive

    - name: Install dependencies
      run: |
        sudo apt-get update
        sudo apt-get install -y \
          build-essential cmake pkg-config \
          libev-dev libevdev-dev libgtk-3-dev \
          libgl1-mesa-dev libglu1-mesa-dev libx11-dev libxrandr-dev libxi-dev libegl1-mesa-dev \
          libavcodec-dev libavformat-dev libavutil-dev libswresample-dev libswscale-dev libudev-dev \
          qtbase5-dev qtdeclarative5-dev qt5-qmake qttools5-dev qttools5-dev-tools libqt5svg5-dev libqt5websockets5-dev libqt5multimedia5-dev libqt5serialport5-dev \
          qt6-base-dev qt6-declarative-dev qt6-svg-dev qt6-tools-dev qt6-tools-dev-tools qt6-wayland-dev qt6-multimedia-dev qt6-networkauth-dev qt6-quickcontrols2-dev qt6-quick3d-dev qt6-quick3dphysics-dev qt6-quicktemplates2-dev qt6-script-dev qt6-sensors-dev qt6-webengine-dev qt6-websockets-dev qt6-x11extras-dev qt6-xmlpatterns-dev qt6-charts-dev qt6-datavis3d-dev qt6-serialport-dev qt6-virtualkeyboard-dev qt6-location-dev qt6-positioning-dev qt6-3dcore-dev qt6-3dextras-dev qt6-3drender-dev qt6-3dinput-dev qt6-3dlogic-dev qt6-3danimation-dev qt6-3dquick-dev qt6-3dquickanimation-dev qt6-3dquickextras-dev qt6-androidextras-dev qt6-connectivity-dev qt6-gamepad-dev qt6-scxml-dev qt6-scripttools-dev qt6-serialbus-dev qt6-serialport-dev qt6-speech-dev qt6-webenginecore-dev qt6-webenginewidgets-dev


    - name: Create build directory
      run: mkdir build

    - name: Configure CMake
      working-directory: build
      env:
        CMAKE_POLICY_VERSION_MINIMUM: "3.5"
      run: cmake .. -DLINUX_LOCAL_DEV=true

    - name: Compile with make
      working-directory: build
      run: make -j$(nproc)

    - name: Verify Build Success
      if: success()
      run: echo "✅ Build completed successfully!"

    - name: Notify on Failure
      if: failure()
      run: echo "❌ Build failed!"
